### ISSUE TITLE
Error building on Mac Os

### ISSUE THREAD

**Issue by korhan0508** [google/shaka-player#1146]
**What version of Shaka Player are you using**:
latest version ( git clone https://github.com/google/shaka-player.git)

**What browser and OS are you using**:
Mac osX
python 2.7.10
java 1.8
node 6.12
mpm 3.1.1

**What did you do?**
I downloaded the first thing git clone https://github.com/google/shaka-player.git
after cd shaka-player 
finally python build/all.py

----->> when I compile it gives the following error

[INFO] Checking that the build files are complete...
[INFO] Checking the tests for type errors...
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

No enum constant com.google.javascript.jscomp.parsing.TypeTransformationParser.Keywords.MAPUNİON
  Node(FUNCTION ): /Users/USERNAME/www/shaka-player/lib/net/networking_engine.js:262:47
shaka.net.NetworkingEngine.prototype.destroy = function() {
  Parent(ASSIGN): /Users/USERNAME/www/shaka-player/lib/net/networking_engine.js:262:0
shaka.net.NetworkingEngine.prototype.destroy = function() {

	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:796)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:766)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:736)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1093)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:492)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1898)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

No enum constant com.google.javascript.jscomp.parsing.TypeTransformationParser.Keywords.MAPUNİON
  Node(FUNCTION ): /Users/korhan/www/shaka-player/lib/net/networking_engine.js:262:47
shaka.net.NetworkingEngine.prototype.destroy = function() {
  Parent(ASSIGN): /Users/korhan/www/shaka-player/lib/net/networking_engine.js:262:0
shaka.net.NetworkingEngine.prototype.destroy = function() {

	at java.lang.Enum.valueOf(Enum.java:238)
	at com.google.javascript.jscomp.parsing.TypeTransformationParser$Keywords.valueOf(TypeTransformationParser.java:55)
	at com.google.javascript.jscomp.TypeTransformation.nameToKeyword(TypeTransformation.java:127)
	at com.google.javascript.jscomp.TypeTransformation.evalInternal(TypeTransformation.java:276)
	at com.google.javascript.jscomp.TypeTransformation.eval(TypeTransformation.java:263)
	at com.google.javascript.jscomp.TypeTransformation.eval(TypeTransformation.java:246)
	at com.google.javascript.jscomp.TypeInference.evaluateTypeTransformations(TypeInference.java:1390)
	at com.google.javascript.jscomp.TypeInference.inferTemplatedTypesForCall(TypeInference.java:1427)
	at com.google.javascript.jscomp.TypeInference.backwardsInferenceFromCallSite(TypeInference.java:1054)
	at com.google.javascript.jscomp.TypeInference.traverseCall(TypeInference.java:960)
	at com.google.javascript.jscomp.TypeInference.traverse(TypeInference.java:344)
	at com.google.javascript.jscomp.TypeInference.traverseChildren(TypeInference.java:1492)
	at com.google.javascript.jscomp.TypeInference.traverseReturn(TypeInference.java:503)
	at com.google.javascript.jscomp.TypeInference.traverse(TypeInference.java:444)
	at com.google.javascript.jscomp.TypeInference.flowThrough(TypeInference.java:188)
	at com.google.javascript.jscomp.TypeInference.branchedFlowThrough(TypeInference.java:200)
	at com.google.javascript.jscomp.TypeInference.branchedFlowThrough(TypeInference.java:70)
	at com.google.javascript.jscomp.DataFlowAnalysis$BranchedForwardDataFlowAnalysis.flow(DataFlowAnalysis.java:456)
	at com.google.javascript.jscomp.DataFlowAnalysis.analyze(DataFlowAnalysis.java:211)
	at com.google.javascript.jscomp.DataFlowAnalysis.analyze(DataFlowAnalysis.java:179)
	at com.google.javascript.jscomp.TypeInferencePass.inferScope(TypeInferencePass.java:119)
	at com.google.javascript.jscomp.TypeInferencePass$SecondScopeBuildingCallback.enterScope(TypeInferencePass.java:147)
	at com.google.javascript.jscomp.NodeTraversal.pushScope(NodeTraversal.java:775)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:677)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:624)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:640)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:734)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:658)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:734)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:658)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:734)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:611)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:637)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:734)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:658)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:734)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:658)
	at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:371)
	at com.google.javascript.jscomp.TypeInferencePass.inferAllScopes(TypeInferencePass.java:110)
	at com.google.javascript.jscomp.TypeInferencePass.process(TypeInferencePass.java:72)
	at com.google.javascript.jscomp.DefaultPassConfig$45$1.process(DefaultPassConfig.java:1692)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:936)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:825)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:92)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:769)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:766)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:91)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No enum constant com.google.javascript.jscomp.parsing.TypeTransformationParser.Keywords.MAPUNİON
	... 53 more
[ERROR] Build failed

**Comment by nicktruch** [comment]
I get an error too but not quite the same :
```
Traceback (most recent call last):
  File "build/all.py", line 20, in <module>
    import build
  File "/Users/truchaud/Sites/shaka-player/build/build.py", line 472
    print 'Usage:', sys.argv[0], """[options] [commands]
                 ^
SyntaxError: Missing parentheses in call to 'print'
```
MacOS 10.13.1
Python 3.6.2
Java 1.8.0_151
Node v9.2.0
Npm 5.5.1

**Comment by theodab** [comment]
@nicktruch, you're getting that error because you are trying to run the build script with Python v3, which changed how `print` works. The build script is designed to work with Python v2.7.

**Comment by theodab** [comment]
@korhan0508 Could you try updating npm? That's a rather old version, and apparently has some issues when installing modules. I tried to downgrade to 3.1.1 to reproduce your problem but npm seems to have some bug at the moment that makes downgrading difficult.

**Comment by joeyparrish** [comment]
@korhan0508, we are unable to reproduce.  We expect that you need to update npm.  If this does not work for you, please let us know and we can reopen the issue and help you further.  Thanks!
