### ISSUE TITLE
Rapidly clicking "Load" in the demo produces errors

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1422]
To reproduce, click "Load" in the demo, then click it again before the load is complete.  It may help to throttle your network connection.  From this hotel wifi, I can reproduce if I click twice, roughly 1/2 second apart.

In the latest release, I get "Cannot read property 'retryParameters' of null".  In the nightly, I get "Shaka Error PLAYER.OPERATION_ABORTED ()".

**Comment by joeyparrish** [comment]
To reproduce at the office, I had to use Chrome's "Slow 3G" emulation in the network panel of the debugger.

Here's a stack trace:

```
Error: Shaka Error PLAYER.OPERATION_ABORTED ()
    at new shaka.util.Error (http://localhost/shaka/lib/util/error.js:89:13)
    at abort (http://localhost/shaka/lib/util/abortable_operation.js:168:25)
    at shaka.util.AbortableOperation [as onAbort_] (http://localhost/shaka/lib/util/abortable_operation.js:216:15)
    at shaka.util.AbortableOperation.abort (http://localhost/shaka/lib/util/abortable_operation.js:120:17)
    at operations_.forEach (http://localhost/shaka/lib/util/operation_manager.js:56:23)
    at Array.forEach (<anonymous>)
    at shaka.util.OperationManager.destroy (http://localhost/shaka/lib/util/operation_manager.js:50:22)
    at shaka.dash.DashParser.stop (http://localhost/shaka/lib/dash/dash_parser.js:363:33)
    at shaka.Player.cancelLoad_ (http://localhost/shaka/lib/player.js:208:31)
    at shaka.Player.unload (http://localhost/shaka/lib/player.js:1341:14)
```

**Comment by joeyparrish** [comment]
The "Fast 3G" setting also works for repro.  Also, instead of clicking "Load" twice, you can click "Load", then "Unload".

**Comment by joeyparrish** [comment]
I misread the stack trace.  `OperationManager.destroy` does not return a rejected Promise.  The error object was created inside that method, but the rejected Promise happened at `player.load()`, which is correct.  The problem is that we're dispatching `OPERATION_ABORTED` from `load()` instead of `LOAD_INTERRUPTED`.  The demo app ignores `LOAD_INTERRUPTED`, as it should.

**Comment by joeyparrish** [comment]
The bug does not affect v2.3.x.
