### ISSUE TITLE
NPM returned non-zero exit status 1

### ISSUE THREAD

**Issue by SIX10** [google/shaka-player#1577]
Hi, I have seen this question before but the solutions did not work. Here is my log, and also, I got something saying I should update something so I wouldn't be vulnerable to ReDoS, can anyone tell me what and how if needed?
```cyberia@MainServer:~/shaka-player$ sudo python build/all.py 
\[INFO] Generating Closure dependencies...
/home/cyberia/shaka-player/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/cyberia/shaka-player/node_modules/wd/build'
    at Object.mkdirSync (fs.js:731:3)
    at sync (/home/cyberia/shaka-player/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/home/cyberia/shaka-player/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.10.3 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.10.3 install script.
cyberia@MainServer:~/shaka-player$ sudo python build/all.py 
[INFO] Generating Closure dependencies...
/home/cyberia/shaka-player/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/cyberia/shaka-player/node_modules/wd/build'
    at Object.mkdirSync (fs.js:731:3)
    at sync (/home/cyberia/shaka-player/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/home/cyberia/shaka-player/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.10.3 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.10.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cyberia/.npm/_logs/2018-09-11T02_56_07_199Z-debug.log
Traceback (most recent call last):
  File "build/all.py", line 98, in <module>
    shakaBuildHelpers.run_main(main)
  File "/home/cyberia/shaka-player/build/shakaBuildHelpers.py", line 301, in run_main
    sys.exit(main(sys.argv[1:]))
  File "build/all.py", line 62, in main
    code = check.main(check_args)
  File "/home/cyberia/shaka-player/build/check.py", line 198, in main
    if not shakaBuildHelpers.update_node_modules():
  File "/home/cyberia/shaka-player/build/shakaBuildHelpers.py", line 279, in update_node_modules
    execute_get_output([cmd, 'install'])
  File "/home/cyberia/shaka-player/build/shakaBuildHelpers.py", line 147, in execute_get_output
    raise subprocess.CalledProcessError(obj.returncode, args[0], stdout)
subprocess.CalledProcessError: Command 'npm' returned non-zero exit status 1```

**Comment by TheModMaker** [comment]
What platform are you running on?  Did you try deleting everything and doing a clean `git clone`?  What is the output of `ls -ld /home/cyberia/shaka-player/node_modules/wd/build`?  What is the output of `npm -v`?

> I got something saying I should update something so I wouldn't be vulnerable to ReDoS, can anyone tell me what and how if needed?

We don't use the NPM modules for anything except testing, so the versions of the packages we use are probably out of date, and we know that some packages have some really outdated dependencies.  So I don't think there is anything you can do to fix that.

**Comment by SIX10** [comment]
Clean git clone does not work. No folder named wd/build apparently. NPM version is 6.4.1

**Comment by TheModMaker** [comment]
Maybe caused by https://github.com/admc/wd/issues/483?  Try `npm install --unsafe-perm`.

**Comment by joeyparrish** [comment]
You definitely shouldn't be using "sudo" for any of this.  Shaka Player doesn't require root, and it doesn't require global installation of any dependencies.  Try starting over without sudo.

**Comment by SIX10** [comment]
Okay, didn't use sudo, and it started giving me a error about something "illegal" (cant remember the exact error message) haven't checked if it compiled yet though.

**Comment by theodab** [comment]
Knowing the exact error message would be helpful.

**Comment by SIX10** [comment]
Here is the output:
``cyberia@MainServer:~/shaka-player/build$ python all.py 
[INFO] Generating Closure dependencies...
[INFO] Running eslint...
[INFO] Running htmlhint...

   Config loaded: /home/cyberia/shaka-player/.htmlhintrc

   Config loaded: /home/cyberia/shaka-player/.htmlhintrc

   Config loaded: /home/cyberia/shaka-player/.htmlhintrc

Scanned 3 files, no errors found (36 ms).
[INFO] Checking that the build files are complete...
[INFO] Checking the tests for type errors...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/cyberia/shaka-player/third_party/closure/compiler.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Checking the usability of generated externs...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/cyberia/shaka-player/third_party/closure/compiler.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Building the docs...
fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, open 'docs/api/fonts/OpenSans-Bold-webfont.eot'
    at Object.openSync (fs.js:436:3)
    at Object.exports.copyFileSync (/home/cyberia/shaka-player/node_modules/jsdoc/lib/jsdoc/fs.js:110:16)
    at /home/cyberia/shaka-player/docs/jsdoc-template/publish.js:611:12
    at Array.forEach (<anonymous>)
    at Object.exports.publish (/home/cyberia/shaka-player/docs/jsdoc-template/publish.js:607:17)
    at Object.module.exports.cli.generateDocs (/home/cyberia/shaka-player/node_modules/jsdoc/cli.js:446:35)
    at Object.module.exports.cli.processParseResults (/home/cyberia/shaka-player/node_modules/jsdoc/cli.js:397:20)
    at module.exports.cli.main (/home/cyberia/shaka-player/node_modules/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/home/cyberia/shaka-player/node_modules/jsdoc/cli.js:189:5)
    at /home/cyberia/shaka-player/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/home/cyberia/shaka-player/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by joeyparrish** [comment]
`WARNING: An illegal reflective access operation has occurred` and related messages seem to be ignorable.  I suspect it has something to do with the version of Java you're running, which may dislike something the compiler (which is written in Java) is doing.

The only error here is in building the docs.  Jsdoc can't open a file in your sources.

I suspect you ran something with sudo before this point.  You should definitely not be using sudo *at all* in Shaka Player development.  It is unnecessary, and you may wind up with certain files only readable by root.

I can reproduce this by taking away my own access to docs/api:

```sh
$ sudo chown root docs/api
$ sudo chmod 700 docs/api
$ ./build/docs.py
[INFO] Building the docs...
/path/to/shaka/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/path/to/shaka/docs/api/fonts'
```

You must not have wiped everything out since you used sudo, or you may have used sudo in your working directory again since you re-cloned everything.  Please run the following commands to wipe out your broken Shaka Player folder and get a clean copy that is owned by you, the user, instead of root:

```sh
# go to your home directory:
cd

# use sudo to wipe out what you have,
# since some of your files are clearly owned by root already
sudo rm -rf shaka-player

# get a fresh copy, NOT with sudo
git clone https://github.com/google/shaka-player

# build NOT with sudo
cd shaka-player
./build/all.py
```

Does this help?

**Comment by SIX10** [comment]
Okay, thanks so much, yea I think I did it with sudo or as root in the beginning.

**Comment by joeyparrish** [comment]
I'm glad we were able to help.  Enjoy Shaka Player!
