### ISSUE TITLE
error for encrypted live channels

### ISSUE THREAD

**Issue by randeeppr** [google/shaka-player#202]
Hi,

I get this error when I play widevine encrypted live content in chrome. on demand videos are playing without issues. HDCP and CGMS is not enabled.
```
CustomEvent {isTrusted: false, srcElement: null, target: s…a.p…r.DashVideoSource, currentTarget: s…a.p…r.Player}bubbles: truecancelBubble: falsecancelable: falsecurrentTarget: shaka.player.PlayerdefaultPrevented: falsedetail: Error: The key system has restricted all video tracks.
    at shaka.player.StreamVideoSource.onKeyStatusesChange (http://vod.domain.com/newshaka/shaka-player-master/lib/player/stream_video_source.js:1069:15)
    at shaka.media.EmeManager.onKeyStatusesChange_ (http://vod.domain.com/newshaka/shaka-player-master/lib/media/eme_manager.js:675:21)message: "The key system has restricted all video tracks."stack: (...)get stack: ()set stack: ()type: "drm"__proto__: DefineError.bhconstructor: Error()arguments: nullcaller: nullcaptureStackTrace: captureStackTrace()length: 1name: "Error"prototype: DefineError.bhstackTraceLimit: 10__proto__: ()<function scope>No Scopesmessage: ""name: "Error"toString: toString()__proto__: ObjecteventPhase: 0isTrusted: falseisTrusted: falsepath: Array[0]length: 0__proto__: Array[0]returnValue: truesrcElement: nulltarget: shaka.player.DashVideoSourcetimeStamp: 1444758973287type: "error"__proto__: CustomEventbubbles: (...)cancelBubble: (...)cancelable: (...)constructor: CustomEvent()currentTarget: (...)defaultPrevented: (...)detail: (...)get detail: ()eventPhase: (...)initCustomEvent: initCustomEvent()path: (...)returnValue: (...)srcElement: (...)target: (...)timeStamp: (...)type: (...)__proto__: Eventapp.onPlayerError_ @ app.js:962shaka.util.FakeEventTarget.recursiveDispatch_ @ fake_event_target.js:143shaka.util.FakeEventTarget.recursiveDispatch_ @ fake_event_target.js:156shaka.util.FakeEventTarget.dispatchEvent @ fake_event_target.js:121shaka.player.StreamVideoSource.onKeyStatusesChange @ stream_video_source.js:1072shaka.media.EmeManager.onKeyStatusesChange_ @ eme_manager.js:675
stream.js:694 Stream video/mp4: stream has started.
```
What can be the issue?

Regards,
Randeep

**Comment by tdrews** [comment]
To help narrow down the problem, can you enable debug logging? You will then see the key status for each key.

**Comment by randeeppr** [comment]
How can I enable it?
I have enabled eme_logger in chrome.

**Comment by tdrews** [comment]
You can either use the library in uncompiled mode, or you can use the library in compiled mode with debug logging by changing `-D shaka.log.MAX_LOG_LEVEL=0` to `-D shaka.log.MAX_LOG_LEVEL=4` in build/lib.sh before executing build/all.sh

**Comment by joeyparrish** [comment]
In an uncompiled build, you can set the log level at runtime using [shaka.log.setLevel()](https://github.com/google/shaka-player/blob/master/lib/debug/log.js#L102).

**Comment by randeeppr** [comment]
@tdrews @joeyparrish 
it was an issue related to widevine and CGMS flag. They have given me a workaround. You can internally check with them. The ticket number is 5-2916000008909.

Thanks and regards,
Randeep

**Comment by randeeppr** [comment]
Latest update is that it is related to  chrome browser.
