### ISSUE TITLE
HLS playback fails if we don't wait for attachment to video element

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2326]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master

**Can you reproduce the issue with our latest release version?**
No, not reproducible with v2.5.x branch.  I'm not yet sure when this problem was introduced.

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Unit tests

**If custom app, can you reproduce the issue using our demo app?**
Likely not, because it depends on timing

**What browser and OS are you using?**
Chrome 79 stable & Firefox 68 ESR on Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Any HLS asset

**What did you do?**
Create a player with the video element as an argument, which implies attaching to that video element.  Without waiting for attachment, immediately call load() on an HLS asset.

In my case, I'm running the external asset playback tests with --external.

**What did you expect to happen?**
I would expect that the player would load content after attaching to the video element.

**What actually happened?**

An exception is thrown from Player during shouldUseSrcEquals_.  This is easiest to see from the integration tests with --external:

	TypeError: Cannot read property 'canPlayType' of null
	    at <Jasmine>
	    at _class.shouldUseSrcEquals_ (lib/player.js:1085:42 <- lib/player.js:37299:69)
	    at _class.load (lib/player.js:983:30 <- lib/player.js:37137:57)
	    at _callee3$ (test/player_external.js:139:21 <- test/player_external.js:190:31)
	    at tryCatch (node_modules/babel-polyfill/dist/polyfill.js:6900:40)
	    at Generator.invoke [as _invoke] (node_modules/babel-polyfill/dist/polyfill.js:7138:22)
	    at Generator.prototype.<computed> [as next] (node_modules/babel-polyfill/dist/polyfill.js:6952:21)
	    at step (test/player_external.js:3:191)
	    at test/player_external.js:3:437
	    at <Jasmine>
	    at UserContext.<anonymous> (test/player_external.js:3:99)

Changing the test's beforeEach to async and changing `player = new compiledShaka(video);` to `player = new compiledShaka(); await player.attach(video);` is an effective workaround, but the API should work with a constructor-provided video element.

Since external asset tests don't run by default, we should write a new test for this.  It shouldn't be too tough, I would expect.

**Comment by joeyparrish** [comment]
Based on git bisect and the integration tests with --external, this was first broken in 6667ea5edf0ae030615c0806bec6b68dd09566e1, "Avoid Platform.supportsMediaType when loading", a change made to simplify Shaka Player Embedded.

**Comment by joeyparrish** [comment]
This bug does not affect any release versions.
