### ISSUE TITLE
DRM.NO_RECOGNIZED_KEY_SYSTEMS Error - Shaka player Fairplay

### ISSUE THREAD

**Issue by kubrasonmez** [google/shaka-player#2820]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
IOS 13.3.1 

**What are the manifest and license server URIs?**

You can find all files (.mpd, .m3u8, .js, .html) below : 
https://drive.google.com/drive/folders/1KXfcL3k8A5ANZJvBU2u_9ShvLQ-beEGq?usp=sharing 

**What did you do?**
We tried to play on safari but we got shaka player error . 

You can find all files we used (.mpd, .m3u8, .js, .html) below : 
https://drive.google.com/drive/folders/1KXfcL3k8A5ANZJvBU2u_9ShvLQ-beEGq?usp=sharing 

**What did you expect to happen?**
Play without issues

**What actually happened?**
When trying to play, I'm gettting error below :

Error Code: 6000
"Shaka Error DRM.NO_RECOGNIZED_KEY_SYSTEMS ()"

"Error: Shaka Error DRM.NO_RECOGNIZED_KEY_SYSTEMS ()
    at new shaka.util.Error (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:177:737)
    at $jscomp.generator.Engine_.program_ (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:279:238)
    at $jscomp.generator.Engine_.nextStep_ (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:36:105)
    at $jscomp.generator.Engine_.next_ (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:32:234)
    at $jscomp.generator.Generator_.next (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:37:73)
    at http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:45:230
    at new Promise (<anonymous>)
    at Object.$jscomp.asyncExecutePromiseGenerator (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:45:123)
    at Object.$jscomp.asyncExecutePromiseGeneratorProgram (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:45:419)
    at shaka.media.DrmEngine.queryMediaKeys_ (http://sawpcorneatabl/fairplay/shaka-player.compiled.debug.js:279:131)"

**Comment by theodab** [comment]
Shaka Player only supports FairPlay via native browser playback. That error suggests that Shaka Player is trying to play the content itself... but most iOS devices don't support MediaSource, so Shaka Player should be defaulting to native playback. Are you on an iPad? [Supposedly MediaSource is available on those](https://caniuse.com/#feat=mediasource), though I don't have a real iPad to confirm that on.

Also, the files you shared are confusing me. An HLS stream is provided, but the code snippet is pointing to the link [http://tableau.cornea.aero/fairplay/stream.mpd](http://tableau.cornea.aero/fairplay/stream.mpd) instead... which is a link that doesn't seem to work, and also doesn't make sense because I don't think MPEG-Dash streams can have FairPlay encryption at all. The `stream.mpd` file inside the drive, if that is what that link is, is encrypted with ClearKey encryption. Is this the actual code you are using?
