### ISSUE TITLE
Dependencies in documentation need to be updated.

### ISSUE THREAD

**Issue by atanaschristov** [google/shaka-player#2913]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
building process

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
linux. No browser needed.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
Irrelevant

**What did you do?**
Dependencies from the docs: https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html
```
You can build Shaka on Linux, Windows, or Mac. To get the sources and compile the library, you will need:

Git v1.9+
Python v2.7 or v3.5+
Java Runtime Environment v8+
NodeJS v8+
```

My environment:
```
$python --version
Python 2.7.18
$ java -version
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
$ node --version
v8.10.0
```
Result:
```
$ python build/all.py 
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Linting CSS...
/home/subnetcat/data/MassiveProjects/shaka-player/node_modules/stylelint/node_modules/get-stdin/index.js:13
	for await (const chunk of stdin) {
	    ^^^^^

SyntaxError: Unexpected reserved word
    at NativeCompileCache._moduleCompile (/home/subnetcat/data/MassiveProjects/shaka-player/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/home/subnetcat/data/MassiveProjects/shaka-player/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/home/subnetcat/data/MassiveProjects/shaka-player/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/subnetcat/data/MassiveProjects/shaka-player/node_modules/stylelint/lib/cli.js:9:18)
    at Module._compile (/home/subnetcat/data/MassiveProjects/shaka-player/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
```

**What did you expect to happen?**
To be able to build the library and the demo

**What actually happened?**
Wasn't able to build it with the dependency requirements provided by docs. If I set the node version to 10.x.x. I'm able to build the libraries. Please update the documentation

**Comment by joeyparrish** [comment]
You are correct.  Looks like stylelint requires node 10.  Thanks for pointing this out!
