### ISSUE TITLE
Can't load "controls.css" file with tutorial example.

### ISSUE THREAD

**Issue by JorViteri** [google/shaka-player#3000]
Hi, I'm new working with Shaka player thus I started with the tutorials. Right now I am trying to work with the UI in order to add more options, such as a "quality" selector. The problem is that, even though I'm following the code from the [tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html), I'm getting the follwoing error when testing my website:
`Refused to apply style from '.../dist/controls.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

I understand that the "controls.css" is reachable from the link to the "shaka-player.compiled.js", so I do not understand what is missing.
In the following lines I attach both my HTML and Javascript code.

**-HTML**
```
<!DOCTYPE html>
<html lang="eng" class="mdl-js">
<head>
  <meta charset="utf-8"/>
  <!-- Shaka Player compiled library: -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.5/shaka-player.compiled.js"></script>
  <!-- Shaka Player ui compiled library default CSS: -->
  <link rel="stylesheet" type="text/css" href="dist/controls.css">
  <!-- Your application source: -->
  <script src="js/main.js"></script>
</head>
<body>
<!-- The data-shaka-player-container tag will make the UI library place the controls in this div.
   The data-shaka-player-cast-receiver-id tag allows you to provide a Cast Application ID that
     the cast button will cast to; the value provided here is the sample cast receiver. -->
<div data-shaka-player-container style="max-width:40em"
     data-shaka-player-cast-receiver-id="930DEB06">
  <video autoplay data-shaka-player id="video"
         width="640"
         poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
         controls ></video>

</div>
</body>
</html>
```
**-Javascript**
```
const manifestUri = 'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd';

function initApp() {
  // Install built-in polyfills to patch browser incompatibilities.
  shaka.polyfill.installAll();

  // Check to see if the browser supports the basic APIs Shaka needs.
  if (shaka.Player.isBrowserSupported()) {
    // Everything looks good!
    initPlayer();
  } else {
    // This browser does not have the minimum set of APIs we need.
    console.error('Browser not supported!');
  }
}

async function initPlayer() {
  // Create a Player instance.
  const video = document.getElementById('video');
  const ui = video['ui'];
  const controls = ui.getControls();
  const player = new shaka.Player(video);

  // Attach player to the window to make it easy to access in the JS console.
  window.player = player;
  window.ui = ui;

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);
  controls.addEventListener('error', onUIErrorEvent);

  // Try to load a manifest.
  // This is an asynchronous process.
  try {
    await player.load(manifestUri);
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  } catch (e) {
    // onError is executed if the asynchronous load fails.
    onError(e);
  }
}

function onPlayerErrorEvent(errorEvent) {
  // Extract the shaka.util.Error object from the event.
  onPlayerError(event.detail);
}

function onPlayerError(error) {
  // Handle player error
  console.error('Error code', error.code, 'object', error);
}

function onUIErrorEvent(errorEvent) {
  // Extract the shaka.util.Error object from the event.
  onPlayerError(event.detail);
}

function initFailed(errorEvent) {
  // Handle the failure to load; errorEvent.detail.reasonCode has a
  // shaka.ui.FailReasonCode describing why.
  console.error('Unable to load the UI library!');
}

// Listen to the custom shaka-ui-loaded event, to wait until the UI is loaded.
document.addEventListener('shaka-ui-loaded', initPlayer);
// Listen to the custom shaka-ui-load-failed event, in case Shaka Player fails
// to load (e.g. due to lack of browser support).
document.addEventListener('shaka-ui-load-failed', initFailed);

```

Thank you for your time.

**Comment by theodab** [comment]
I haven't seen this problem before myself, but according to [this stackoverflow question](https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type) that might be the result of the CSS file failing to load (and then the browser intreprets the 404 error as HTML, rather than CSS). I guess how likely that is depends on how you are serving the tutorial code, though.
Oh, and have you run a build command, to actually generate the contents of `dist/controls.css`? Just in case.

**Comment by joeyparrish** [comment]
> might be the result of the CSS file failing to load (and then the browser intreprets the 404 error as HTML, rather than CSS)

I find this very likely.  Looking at your code, I see that you are loading the library from cdnjs, but the CSS locally:

```html
  <!-- Shaka Player compiled library: -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.5/shaka-player.compiled.js"></script>
  <!-- Shaka Player ui compiled library default CSS: -->
  <link rel="stylesheet" type="text/css" href="dist/controls.css">
```

If you haven't compiled the library, or if the source folder isn't the same folder as this HTML, you won't have that controls.css file at that path.  But you can also load the CSS from cdnjs:

```html
  <!-- Shaka Player compiled library: -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.5/shaka-player.compiled.js"></script>
  <!-- Shaka Player ui compiled library default CSS: -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.0.5/controls.css">
```

Does this help?

**Comment by JorViteri** [comment]
Hi again.
First I would like to apologise for answering so late, but I had been quite busy lately.
After reading your messages I can say that my fault was that I misunderstood the first part of the tutorial, thus not having the correct "dist" folder within my project. That being said, I checked the the "dist" folder after executing "python build/all.py" and, even thought there are some javascript files, controls.css is still missing. When executing the build command, no error message appears, is another step missing?.

Meanwhile I will try loading the CSS from cdnjs, thank you very much!

**Comment by joeyparrish** [comment]
I wanted to make sure that we didn't have a bug in which my local working directory state was the only reason the CSS build was working.  So I checked out a clean copy from GitHub and built everything from scratch:

```sh
git clone https://github.com/google/shaka-player
cd shaka-player
python build/all.py
ls dist/controls.css
```

This is working correctly for me.  Do you get different results for the same commands?  What OS are you using?  Can you please post the complete output of those commands?  Thanks!

**Comment by JorViteri** [comment]
I followed your instructions in order to generate a clean complitation and there were some problems, though I was able to generate it at the end.
My OS is Windows 10, though I ended using the Ubuntu WSL as you will see.
The problem started with the command "python build/all.py" in the Windows cmd, which gave me the following error:

```
Traceback (most recent call last):
  File "...\shaka-player\build\all.py", line 150, in <module>
    shakaBuildHelpers.run_main(main)
  File "...\shaka-player\build\shakaBuildHelpers.py", line 360, in run_main
    sys.exit(main(sys.argv[1:]))
  File "...\shaka-player\build\all.py", line 92, in main
    if not localizations.generate(parsed_args.force):
  File "...\shaka-player\build\compiler.py", line 501, in generate
    generateLocalizations.main(['--locales'] + locales)
  File "...\shaka-player\build\generateLocalizations.py", line 252, in main
    combined_localizations[locale] = json.load(f)
  File "C:\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 318: character maps to <undefined>

```
After this I decided to try the it in the Ubuntu terminal. It gave me a different error:
```
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting CSS...
[ERROR] *** A required dependency is missing: node
.../shaka-player$ python build/all.py
[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...
[ERROR] *** A required dependency is missing: node
```

But after this error, a different one showed up in the Windows cmd if I tried the command just one more time:

```
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting CSS...
Error: No files matching the pattern "...\shaka-player\demo\cast_receiver\receiver_app.css, ...\shaka-player\demo\demo.less,
 ...\shaka-player\ui\controls.less, ...\shaka-player\ui\less\ad_controls.less, ...\shaka-player\ui\less\buttons.less,
 ...\shaka-player\ui\less\containers.less, ...\shaka-player\ui\less\general.less, ...\shaka-player\ui\less\other_elements.less,
 ...\shaka-player\ui\less\overflow_menu.less, ...\shaka-player\ui\less\range_elements.less, ...\shaka-player\ui\less\spinner.less" were found.
    at ...\shaka-player\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I saw that this error had a fix described in one [post](https://github.com/google/shaka-player/issues/2985) of the project, so I applied it, launched it again in the Ubuntu WSL (got the same "missing dependency error") and finally tried  my luck again in the Windows cm., It was a success.

```
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...
[INFO] Linting HTML...

   Config loaded: ...\shaka-player\.htmlhintrc

   Config loaded: ...\shaka-player\.htmlhintrc

   Config loaded: ...\shaka-player\.htmlhintrc

Scanned 3 files, no errors found (34 ms).
[INFO] Checking that the build files are complete...
[INFO] Checking for common misspellings...
[INFO] Checking correct usage of eslint-disable...
[INFO] Checking the tests for type errors...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Building the docs...
[INFO] Compiling the library (ui, debug)...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Compiling the library (compiled, debug)...
[INFO] Compiling the demo app (debug)...
[INFO] Compiling the receiver app (debug)...
[INFO] Compiling the library (ui, release)...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Compiling the library (compiled, release)...
[INFO] Compiling the demo app (release)...
[INFO] Compiling the receiver app (release)...

```
This is what I have for the moment.

**Comment by joeyparrish** [comment]
> [ERROR] *** A required dependency is missing: node

This means you don't have nodejs installed in Ubuntu.

> tried my luck again in the Windows cm., It was a success.

Awesome!  I'm glad you were able to make this work in Windows.  Is there anything else we can help you with?

**Comment by JorViteri** [comment]
Yes, all my questions have been answered, you can close the issue.
Thank you for you time!
