### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by randeeppr** [google/shaka-player#314]
Hi,
I'm getting the following error while compiling. I downloaded the latest one.
```
[root@origin shaka-player-master]# ./build/all.py
Traceback (most recent call last):
  File "./build/all.py", line 17, in <module>
    import check
  File "/var/www/html/shaka2/shaka-player-master/build/check.py", line 24, in <module>
    import build
  File "/var/www/html/shaka2/shaka-player-master/build/build.py", line 83, in <module>
    '-D', 'GIT_VERSION="%s"' % shakaBuildHelpers.calculateVersion()
  File "/var/www/html/shaka2/shaka-player-master/build/shakaBuildHelpers.py", line 95, in calculateVersion
    return gitVersion()
  File "/var/www/html/shaka2/shaka-player-master/build/shakaBuildHelpers.py", line 71, in gitVersion
    return subprocess.check_output(cmdLine).strip()
AttributeError: 'module' object has no attribute 'check_output'
```
My python and java Versions are,
[root@origin shaka-player-master]# python -V
Python 2.6.6
[root@origin shaka-player-master]# java -version
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)

What can be the reason.

**Comment by joeyparrish** [comment]
Hi @randeeppr, the method in that error message (`check_output`) was introduced a little over 5 years ago in Python v2.7.  I will update our docs to state that v2.7 is the minimum version required by the build scripts.  In the mean time, please update to v2.7.  Thanks!
