### ISSUE TITLE
Streaming engine error when switching video streams and no text tracks

### ISSUE THREAD

**Issue by ckelsey** [google/shaka-player#640]
I'm using v2.0.2 and am getting an error when switching video streams by calling Player.selectTrack() which I believe is caused by not having a text track. Here is the stacktrace:

TypeError: Cannot read property 'mimeType' of undefined
    at shaka-player/lib/media/streaming_engine.js:554:15
    at shaka-player/lib/util/map_utils.js:62:16
    at Array.reduce (native)
    at Object.shaka.util.MapUtils.map (shaka-player/lib/util/map_utils.js:60:30)
    at shaka.media.StreamingEngine.initStreams_ (shaka-player/lib/media/streaming_engine.js:552:29)
    at shaka.media.StreamingEngine.notifyNewStream (shaka-player/lib/media/streaming_engine.js:399:15)
    at shaka.media.StreamingEngine.switch (shaka-player/lib/media/streaming_engine.js:416:10)
    at shaka.Player.deferredSwitch_ (shaka-player/lib/player.js:1322:35)

If I do supply a text track and switch video streams, no error at all and everything is fine.

**Comment by joeyparrish** [comment]
The fix for this has just been released in v2.0.3.
