### ISSUE TITLE
Regress shaka-nightly, IE11 & Edge: video is not playing

### ISSUE THREAD

**Issue by Ross-cz** [google/shaka-player#792]
- What version of Shaka Player are you using?
v2.1.0-15-gf992851-debug (https://nightly-dot-shaka-player-demo.appspot.com/demo/)

- Are you using the demo app or your own custom app?
d
- What browser and OS are you using?
Windows, IE11/Edge

- What did you do?
Tried to play any content.

- What did you expect to happen?
Playback starts.

- What actually happened?
TypeError: Unable to get property 'length' of undefined or null reference
Edge stack:
   at shaka.dash.MpdUtils.processXlinks (https://nightly-dot-shaka-player-demo.appspot.com/lib/dash/mpd_utils.js:536:19)
   at shaka.dash.DashParser.prototype.parseManifest_ (https://nightly-dot-shaka-player-demo.appspot.com/lib/dash/dash_parser.js:423:3)
   at Anonymous function (https://nightly-dot-shaka-player-demo.appspot.com/lib/dash/dash_parser.js:394:9)
IE11 stack:
   at shaka.dash.MpdUtils.processXlinks (https://nightly-dot-shaka-player-demo.appspot.com/lib/dash/mpd_utils.js:536:19)
   at shaka.dash.DashParser.prototype.parseManifest_ (https://nightly-dot-shaka-player-demo.appspot.com/lib/dash/dash_parser.js:423:3)
   at Anonymous function (https://nightly-dot-shaka-player-demo.appspot.com/lib/dash/dash_parser.js:394:9)
   at wrapper (https://nightly-dot-shaka-player-demo.appspot.com/lib/polyfill/promise.js:344:9)
   at shaka.polyfill.Promise.flush (https://nightly-dot-shaka-player-demo.appspot.com/lib/polyfill/promise.js:451:7)

**Comment by joeyparrish** [comment]
Thanks for the report.  Looks like our xlink commit broke IE & Edge.  Our build bot is complaining as well, which is good news.  Should be easy to chase down.

**Comment by joeyparrish** [comment]
I updated the nightly build early, so you should see the fix there now.  Thanks again for the report!
