### ISSUE TITLE
"StreamingEngine Live ... seek" test failure on Android

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#966]
We had the following test timeout on Chrome on Android in our nightly test run:

```
Chrome Mobile 61.0.3163 (Android 7.1.1)
  StreamingEngine Live can handle seeks behind availability window FAILED
    Expected null not to be null.
        at test/media/streaming_engine_integration.js:273:31
        at Object.<anonymous> (test/test/util/streaming_engine_util.js:70:16)

    Failed: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (TypeError: Failed to execute 'appendBuffer' on 'SourceBuffer': No function was found that matched the signature provided.)
        at new shaka.util.Error (lib/util/error.js:66:13)
        at shaka.media.MediaSourceEngine.enqueueOperation_ (lib/media/media_source_engine.js:733:28)
        at shaka.media.MediaSourceEngine.appendBuffer (lib/media/media_source_engine.js:386:15)
        at shaka.media.StreamingEngine.<anonymous> (lib/media/streaming_engine.js:1548:52)
        at <anonymous>
```

The next test run, the test passed again.

**Comment by joeyparrish** [comment]
This did not reoccur in the subsequent 50+ nightly runs.  I'm running a stress test now to try to reproduce.

**Comment by joeyparrish** [comment]
Unable to reproduce after 20 more runs.
